from typing import Protocol, runtime_checkable


@runtime_checkable
class ConversationRepositoryProtocol(Protocol):
    async def init_db(self) -> None: ...
    async def create_session(self) -> str: ...
    async def get_session(self, session_id: str) -> dict | None: ...
    async def update_session_state(self, session_id: str, new_state: str) -> None: ...
    async def save(self, user_message: str, ai_response: str, session_id: str) -> None: ...
    async def save_and_transition(
        self, user_message: str, ai_response: str, session_id: str, new_state: str
    ) -> None: ...
    async def get_all(self, limit: int) -> list[dict]: ...
    async def get_by_session_id(self, session_id: str, limit: int) -> list[dict]: ...
    async def get_by_id(self, conversation_id: int) -> dict | None: ...
    async def build_context(self, session_id: str) -> str: ...
    async def build_context_simulation(self, session_id: str) -> str: ...
